/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Models.CVIslemleri;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Image;
import java.awt.Font;
//import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dicle
 */
public class CVFormu extends javax.swing.JFrame {
    CVIslemleri islemler= new CVIslemleri();
    /**
     * Creates new form CVFormu
     */
    public CVFormu() {
        initComponents();
        uni2_txt.setVisible(false);
        bolum2_txt.setVisible(false);
        derece2_combo.setVisible(false);
        butonEksi.setVisible(false);
        uni2_label.setVisible(false);
        bolum2_label.setVisible(false);
        derece2_label.setVisible(false);
        date1_label.setVisible(false);
        date2_label.setVisible(false);
        year1.setVisible(false);
        year2.setVisible(false);
        labelSeviye.setVisible(false);
        dilSeviye.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ad_txt = new javax.swing.JTextField();
        mail_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        adres_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        soyad_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        foto_buton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bolum2_txt = new javax.swing.JTextField();
        derece_combo = new javax.swing.JComboBox<>();
        gpa_txt = new javax.swing.JTextField();
        uni2_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        butonArti = new javax.swing.JToggleButton();
        year2 = new com.toedter.calendar.JYearChooser();
        date2_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bolum2_label = new javax.swing.JLabel();
        derece2_label = new javax.swing.JLabel();
        year1 = new com.toedter.calendar.JYearChooser();
        jLabel14 = new javax.swing.JLabel();
        uni2_txt = new javax.swing.JTextField();
        fakulte_txt = new javax.swing.JTextField();
        butonEksi = new javax.swing.JButton();
        date1_label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bolum_txt = new javax.swing.JTextField();
        uni_txt = new javax.swing.JTextField();
        derece2_combo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        baslangicCombo = new javax.swing.JComboBox<>();
        bitisCombo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        poz_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aciklama_alani = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bitisTCombo = new javax.swing.JComboBox<>();
        firma_txt = new javax.swing.JTextField();
        baslangicTCombo = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kurum_txt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        skill1_txt = new javax.swing.JTextField();
        skill3_txt = new javax.swing.JTextField();
        sertifika_txt = new javax.swing.JTextField();
        dilSeviye = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        labelSeviye = new javax.swing.JLabel();
        noRadio = new javax.swing.JRadioButton();
        skill2_txt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        yesRadio = new javax.swing.JRadioButton();
        alinanTarih = new javax.swing.JLabel();
        alinantarihCombo = new javax.swing.JComboBox<>();
        temizle_buton = new javax.swing.JButton();
        pdfOlustur = new javax.swing.JButton();
        anasayfa_buton = new javax.swing.JButton();
        kaydetButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(171, 198, 210));

        jPanel2.setBackground(new java.awt.Color(171, 198, 210));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 81, 146)), "Kişisel Bilgiler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-Mail:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ad:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Doğum Tarihi:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Soyad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Adres:");

        foto_buton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        foto_buton.setIcon(new javax.swing.ImageIcon("C:\\Users\\dicle\\OneDrive\\Masaüstü\\swingImages\\2.png")); // NOI18N
        foto_buton.setText("Fotoğraf Ekle");
        foto_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foto_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mail_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(adres_txt))
                            .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foto_buton))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyad_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(adres_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(foto_buton)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(171, 198, 210));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 81, 146)), "Eğitim Bilgileri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Fakülte:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bölüm:");

        derece_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lisans Derecesi", "Ön Lisans Derecesi", "Yüksek Lisans Derecesi", "Doktora" }));

        uni2_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uni2_label.setText("Üniversite:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Üniversite:");

        butonArti.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        butonArti.setText("+");
        butonArti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonArtiActionPerformed(evt);
            }
        });

        date2_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date2_label.setText("Başlangıç Tarihi:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Öğrenim Durumu:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("GPA: ");

        bolum2_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bolum2_label.setText("Bölüm:");

        derece2_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        derece2_label.setText("Öğrenim Durumu:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Başlangıç Tarihi:");

        butonEksi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        butonEksi.setText("-");
        butonEksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonEksiActionPerformed(evt);
            }
        });

        date1_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date1_label.setText("Bitiş Tarihi:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Bitiş Tarihi:");

        derece2_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lisans Derecesi", "Ön Lisans Derecesi", "Yüksek Lisans Derecesi", "Doktora" }));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Ekle");

        baslangicCombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        baslangicCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        bitisCombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bitisCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Halen", "2030", "2029", "2028", "2027", "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));
        bitisCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitisComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(gpa_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bitisCombo, 0, 150, Short.MAX_VALUE)
                                    .addComponent(baslangicCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(butonArti))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(derece_combo, 0, 153, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(47, 47, 47))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uni_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(bolum_txt)))
                        .addComponent(fakulte_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uni2_label)
                    .addComponent(bolum2_label)
                    .addComponent(derece2_label)
                    .addComponent(date2_label)
                    .addComponent(date1_label)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(derece2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonEksi)
                    .addComponent(uni2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bolum2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(uni_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uni2_label)
                        .addComponent(uni2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(bolum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bolum2_label)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bolum2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(derece_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(derece2_label)
                    .addComponent(derece2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date2_label)
                        .addComponent(fakulte_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(date1_label)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butonArti)
                            .addComponent(butonEksi)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(baslangicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(gpa_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(bitisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(171, 198, 210));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 81, 146)), "İş Deneyimi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Açıklama:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Başlangıç Tarihi:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Bitiş Tarihi:");

        aciklama_alani.setColumns(20);
        aciklama_alani.setRows(5);
        jScrollPane1.setViewportView(aciklama_alani);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Pozisyon:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Firma Adı:");

        bitisTCombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bitisTCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Halen", "2030", "2029", "2028", "2027", "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        baslangicTCombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        baslangicTCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(poz_txt)
                    .addComponent(firma_txt)
                    .addComponent(bitisTCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(baslangicTCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(firma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(poz_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addComponent(baslangicTCombo))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(bitisTCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        jPanel5.setBackground(new java.awt.Color(171, 198, 210));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 81, 146)), "Beceriler & Sertifikalar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Bilgisayar Becerileri:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Kurum:");

        dilSeviye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Baslangic", "Orta", "Ileri" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("İngilizce:");

        labelSeviye.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelSeviye.setText("Seviye:");

        buttonGroup1.add(noRadio);
        noRadio.setText("Hayır");
        noRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noRadioMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setText("Sertifika:");

        buttonGroup1.add(yesRadio);
        yesRadio.setText("Evet");
        yesRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesRadioMouseClicked(evt);
            }
        });

        alinanTarih.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        alinanTarih.setText("Alınan Tarih:");

        alinantarihCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(labelSeviye)
                                .addGap(71, 71, 71)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dilSeviye, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(yesRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(noRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(skill1_txt)
                                    .addComponent(skill3_txt)
                                    .addComponent(skill2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel21))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(alinanTarih)
                                            .addComponent(jLabel22)))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel19)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kurum_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(sertifika_txt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alinantarihCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(skill1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sertifika_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(skill2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skill3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(yesRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alinanTarih)
                    .addComponent(alinantarihCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dilSeviye, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSeviye))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        temizle_buton.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        temizle_buton.setText("Temizle");
        temizle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizle_butonActionPerformed(evt);
            }
        });

        pdfOlustur.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        pdfOlustur.setText("PDF Oluştur →");
        pdfOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfOlusturActionPerformed(evt);
            }
        });

        anasayfa_buton.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        anasayfa_buton.setText("← Ana Sayfaya Dön");
        anasayfa_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfa_butonActionPerformed(evt);
            }
        });

        kaydetButonu.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        kaydetButonu.setText("Kaydet");
        kaydetButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(anasayfa_buton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temizle_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(kaydetButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pdfOlustur)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temizle_buton)
                            .addComponent(pdfOlustur)
                            .addComponent(kaydetButonu)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(anasayfa_buton)))
                .addGap(178, 178, 178))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void foto_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foto_butonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.DEFAULT));
        lbl_img.setIcon(imageIcon);
      try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_foto_butonActionPerformed

    private void butonArtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonArtiActionPerformed
        uni2_txt.setVisible(true);
        bolum2_txt.setVisible(true);
        derece2_combo.setVisible(true);
        butonEksi.setVisible(true);
        uni2_label.setVisible(true);
        bolum2_label.setVisible(true);
        derece2_label.setVisible(true);
        date1_label.setVisible(true);
        date2_label.setVisible(true);
        year1.setVisible(true);
        year2.setVisible(true);
    }//GEN-LAST:event_butonArtiActionPerformed

    private void butonEksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonEksiActionPerformed
        uni2_txt.setVisible(false);
        bolum2_txt.setVisible(false);
        derece2_combo.setVisible(false);
        butonEksi.setVisible(false);
        uni2_label.setVisible(false);
        bolum2_label.setVisible(false);
        derece2_label.setVisible(false);
        date1_label.setVisible(false);
        date2_label.setVisible(false);
        year1.setVisible(false);
        year2.setVisible(false);
    }//GEN-LAST:event_butonEksiActionPerformed

    private void anasayfa_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfa_butonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_anasayfa_butonActionPerformed

    private void temizle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizle_butonActionPerformed
        ad_txt.setText("");
        soyad_txt.setText("");
        mail_txt.setText("");
        adres_txt.setText("");
        uni_txt.setText("");
        bolum_txt.setText("");
        fakulte_txt.setText("");
        gpa_txt.setText("");
        uni2_txt.setText("");
        bolum2_txt.setText("");
        firma_txt.setText("");
        poz_txt.setText("");
        aciklama_alani.setText("");
        skill1_txt.setText("");
        skill2_txt.setText("");
        skill2_txt.setText("");
        sertifika_txt.setText("");
        kurum_txt.setText("");
    }//GEN-LAST:event_temizle_butonActionPerformed

    private void pdfOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfOlusturActionPerformed
        String ad=ad_txt.getText();
        String soyad=soyad_txt.getText();
        if(ad.equals("") && soyad.equals("")){
            JOptionPane.showMessageDialog(null, "Ad ve Soyad alanı boş geçilemez!");
        }
        SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
        String dogumTarihi=sdf.format(dob.getDate());
        String mail=mail_txt.getText();
        String adres=adres_txt.getText();
        String uni=uni_txt.getText();
        String bolum=bolum_txt.getText();
        String fakulte=fakulte_txt.getText();
        String ogrenimDurumu=derece_combo.getSelectedItem().toString();
        String baslangicTarihi=baslangicCombo.getSelectedItem().toString();
        String bitisTarihi=bitisCombo.getSelectedItem().toString();
        double gpa=Double.valueOf(gpa_txt.getText());
        String firma=firma_txt.getText();
        String pozisyon=poz_txt.getText();
        String baslangicTarihi2=baslangicTCombo.getSelectedItem().toString();
        String bitisTarihi2=bitisTCombo.getSelectedItem().toString();
        String aciklama=aciklama_alani.getText();
        String beceri1=skill1_txt.getText();
        String beceri2=skill2_txt.getText();
        String beceri3=skill3_txt.getText();
        String yabanciDil = null;
        String seviye=dilSeviye.getSelectedItem().toString();
        String sertifika=sertifika_txt.getText();
        String kurum=kurum_txt.getText();
        String sertifikaTarih=alinantarihCombo.getSelectedItem().toString();
        if(yesRadio.isSelected()){
            yabanciDil="Ingilizce";
        }
        
        JFileChooser dialog=new JFileChooser();
        dialog.setSelectedFile(new File(ad+"-"+soyad+"-CV"+".pdf"));
        int dialogResult=dialog.showSaveDialog(null);
          Image image = null;
        try {
            image = Image.getInstance(person_image);
        } catch (BadElementException ex) {
            Logger.getLogger(CVFormu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CVFormu.class.getName()).log(Level.SEVERE, null, ex);
        }
          image.setAbsolutePosition(420f, 700f);
          image.scaleAbsolute(110f,110f);
        if(dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath =dialog.getSelectedFile().getPath();
            try{
            Document myDocument=new Document();
            PdfWriter myWriter=PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
            myDocument.open();
            myDocument.add(image);
            myDocument.add(new Paragraph(ad+" "+soyad,FontFactory.getFont(FontFactory.TIMES_BOLD,28,Font.BOLD))); 
            myDocument.add(new Paragraph(" ")); 
            myDocument.add(new Paragraph("Iletisim Bilgileri ",FontFactory.getFont(FontFactory.TIMES,13,Font.BOLD)));
            if(!mail.equals("")){
            myDocument.add(new Paragraph("E-Mail: "+mail,FontFactory.getFont(FontFactory.TIMES,13))); }
            if(!adres.equals("")){
            myDocument.add(new Paragraph("Adres: "+adres,FontFactory.getFont(FontFactory.TIMES,13)));}
            if(!dogumTarihi.equals("")){
            myDocument.add(new Paragraph("Dogum Tarihi: "+dogumTarihi,FontFactory.getFont(FontFactory.TIMES,13))); }
            myDocument.add(new Paragraph(" "));
            if(!uni.equals("")){
            myDocument.add(new Paragraph("Egitim Bilgileri",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD))); 
            myDocument.add(new Paragraph("Universite: "+uni,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Fakulte ve Bolum: "+bolum+", "+fakulte,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Ogrenim Durumu: "+ogrenimDurumu,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Ortalama: "+gpa,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Baslangic - Bitis: "+baslangicTarihi+" - "+bitisTarihi,FontFactory.getFont(FontFactory.TIMES,13)));} 
            myDocument.add(new Paragraph(" "));
            if(!firma.equals("")){
            myDocument.add(new Paragraph("Deneyimler",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD))); 
            myDocument.add(new Paragraph("Firma Adi: "+firma,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Pozisyon: "+pozisyon,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Tarih: "+baslangicTarihi2+" - "+bitisTarihi2,FontFactory.getFont(FontFactory.TIMES,13))); 
            myDocument.add(new Paragraph("Aciklama: "+aciklama,FontFactory.getFont(FontFactory.TIMES,13))); }
            myDocument.add(new Paragraph(" "));
            myDocument.add(new Paragraph("Beceriler & Sertifikalar ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
            if(!yabanciDil.equals("")){
            myDocument.add(new Paragraph("- Yabanci Diller ",FontFactory.getFont(FontFactory.TIMES,13,Font.BOLD)));  
            myDocument.add(new Paragraph("- "+yabanciDil+" ("+seviye+" Seviye) ",FontFactory.getFont(FontFactory.TIMES,13)));}
            if(!beceri1.equals("") && !beceri2.equals("") && !beceri3.equals("")){
            myDocument.add(new Paragraph("- Bilgisayar Becerileri ",FontFactory.getFont(FontFactory.TIMES,13,Font.BOLD)));  
            myDocument.add(new Paragraph(beceri1,FontFactory.getFont(FontFactory.TIMES,13)));
            myDocument.add(new Paragraph(beceri2,FontFactory.getFont(FontFactory.TIMES,13)));
            myDocument.add(new Paragraph(beceri3,FontFactory.getFont(FontFactory.TIMES,13)));}
            if(!sertifika.equals("")){
            myDocument.add(new Paragraph(" - Sertifikalar ",FontFactory.getFont(FontFactory.TIMES,13,Font.BOLD)));
            myDocument.add(new Paragraph(sertifika+", "+kurum+" ("+sertifikaTarih+")",FontFactory.getFont(FontFactory.TIMES,13))); }          
            
            myDocument.close();
            JOptionPane.showMessageDialog(null,"CV Başarıyla oluşturulmuştur...");
        }
            catch(Exception e){
        }
            
        }
    }//GEN-LAST:event_pdfOlusturActionPerformed

    private void bitisComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitisComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bitisComboActionPerformed

    private void yesRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesRadioMouseClicked
        labelSeviye.setVisible(true);
        dilSeviye.setVisible(true);
    }//GEN-LAST:event_yesRadioMouseClicked

    private void noRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noRadioMouseClicked
        labelSeviye.setVisible(false);
        dilSeviye.setVisible(false);
    }//GEN-LAST:event_noRadioMouseClicked

    private void kaydetButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButonuActionPerformed
        String adi=ad_txt.getText();
        String soyadi=soyad_txt.getText();
        String emaili=mail_txt.getText();
        String adresi=adres_txt.getText();
        String kullaniciAdi=JOptionPane.showInputDialog("Kullanici adinizi giriniz");
        islemler.kisiselBilgiEkle(kullaniciAdi, adi, soyadi, emaili, adresi);
        
        String universite=uni_txt.getText();
        String bolumu=bolum_txt.getText();
        String fakultesi=fakulte_txt.getText();
        double ortalama=Double.valueOf(gpa_txt.getText());
        String derecesi=derece_combo.getSelectedItem().toString();
        islemler.egitimEkle(kullaniciAdi,universite, bolumu, fakultesi, ortalama, derecesi);
        
        String firmasi=firma_txt.getText();
        String pozisyonu=poz_txt.getText();
        String aciklama=aciklama_alani.getText();
        islemler.deneyimEkle(kullaniciAdi, firmasi, pozisyonu, aciklama);
        
        
                        
        
    }//GEN-LAST:event_kaydetButonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CVFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CVFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CVFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CVFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CVFormu().setVisible(true);
            }
        });
    }
String filename=null;
byte[] person_image = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aciklama_alani;
    private javax.swing.JTextField ad_txt;
    private javax.swing.JTextField adres_txt;
    private javax.swing.JLabel alinanTarih;
    private javax.swing.JComboBox<String> alinantarihCombo;
    private javax.swing.JButton anasayfa_buton;
    private javax.swing.JComboBox<String> baslangicCombo;
    private javax.swing.JComboBox<String> baslangicTCombo;
    private javax.swing.JComboBox<String> bitisCombo;
    private javax.swing.JComboBox<String> bitisTCombo;
    private javax.swing.JLabel bolum2_label;
    private javax.swing.JTextField bolum2_txt;
    private javax.swing.JTextField bolum_txt;
    private javax.swing.JToggleButton butonArti;
    private javax.swing.JButton butonEksi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel date1_label;
    private javax.swing.JLabel date2_label;
    private javax.swing.JComboBox<String> derece2_combo;
    private javax.swing.JLabel derece2_label;
    private javax.swing.JComboBox<String> derece_combo;
    private javax.swing.JComboBox<String> dilSeviye;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField fakulte_txt;
    private javax.swing.JTextField firma_txt;
    private javax.swing.JButton foto_buton;
    private javax.swing.JTextField gpa_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaydetButonu;
    private javax.swing.JTextField kurum_txt;
    private javax.swing.JLabel labelSeviye;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField mail_txt;
    private javax.swing.JRadioButton noRadio;
    private javax.swing.JButton pdfOlustur;
    private javax.swing.JTextField poz_txt;
    private javax.swing.JTextField sertifika_txt;
    private javax.swing.JTextField skill1_txt;
    private javax.swing.JTextField skill2_txt;
    private javax.swing.JTextField skill3_txt;
    private javax.swing.JTextField soyad_txt;
    private javax.swing.JButton temizle_buton;
    private javax.swing.JLabel uni2_label;
    private javax.swing.JTextField uni2_txt;
    private javax.swing.JTextField uni_txt;
    private com.toedter.calendar.JYearChooser year1;
    private com.toedter.calendar.JYearChooser year2;
    private javax.swing.JRadioButton yesRadio;
    // End of variables declaration//GEN-END:variables
}
